//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consecutive
    {
        public int id { get; set; }
        public string description { get; set; }
        public int value { get; set; }
        public string prefix { get; set; }
        public Nullable<int> range_int { get; set; }
        public Nullable<int> range_out { get; set; }
    }
}
