//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight_tickets
    {
        public string consecutivo_flight_ticket_id { get; set; }
        public int user_id { get; set; }
        public string consecutive_country_id_FK { get; set; }
    
        public virtual country country { get; set; }
        public virtual user user { get; set; }
    }
}
