//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight
    {
        public string consecutive_flight_id { get; set; }
        public string code { get; set; }
        public string consecutive_airline_id { get; set; }
        public int city_id { get; set; }
        public System.DateTime arrival_date { get; set; }
        public System.TimeSpan arrival_time { get; set; }
        public string consecutive_airport_gate_id_FK { get; set; }
        public string status { get; set; }
        public Nullable<bool> onflight { get; set; }
    
        public virtual airline airline { get; set; }
        public virtual airport_gates airport_gates { get; set; }
        public virtual city city { get; set; }
    }
}
