//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_book
    {
        public int id { get; set; }
        public Nullable<int> user_id_FK { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> action_id { get; set; }
        public string action_type { get; set; }
        public string description { get; set; }
        public string detail_description { get; set; }
    
        public virtual user user { get; set; }
    }
}
