//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vVuelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public string consecutive_reserve_id { get; set; }
        public int user_id { get; set; }
        public string booking_id { get; set; }
        public int amount { get; set; }
        public int total { get; set; }
        public System.DateTime alert { get; set; }
    }
}
