//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vVuelos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vVuelosEntities : DbContext
    {
        public vVuelosEntities()
            : base("name=vVuelosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<airline> airlines { get; set; }
        public virtual DbSet<airport_gates> airport_gates { get; set; }
        public virtual DbSet<card> cards { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<consecutive> consecutives { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<error> errors { get; set; }
        public virtual DbSet<flight_tickets> flight_tickets { get; set; }
        public virtual DbSet<flight> flights { get; set; }
        public virtual DbSet<log_book> log_book { get; set; }
        public virtual DbSet<reservation> reservations { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
