//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vVuelos_paymentEntities : DbContext
    {
        public vVuelos_paymentEntities()
            : base("name=vVuelos_paymentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cards> cards { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<easy_pay> easy_pay { get; set; }
    }
}
