//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cards()
        {
            this.customer = new HashSet<customer>();
        }
    
        public int id { get; set; }
        public string card_number { get; set; }
        public int expiration_month { get; set; }
        public int expiration_year { get; set; }
        public int cvv { get; set; }
        public string issuer { get; set; }
        public Nullable<int> is_credit_card { get; set; }
        public Nullable<int> is_debit_card { get; set; }
        public Nullable<int> credit_limit { get; set; }
        public Nullable<int> balance { get; set; }
        public bool active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer> customer { get; set; }
    }
}
